# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - 'master'
env:
  CI: true

jobs:
  
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      
    - run: npm install
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      
  release:
    if: ${{ github.ref == 'master' }}
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge release -> master
        uses: devmasx/merge-branch@v1.3.0
        with:
          type: now
          from_branch: release
          target_branch: master
          github_token: ${{ github.token }}
    
